on: push
name: Run tests on linux
jobs:
  test_all_platforms:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run tests
        run: go test -race -cover ./...
