on: push
name: Tests on linux
jobs:
  test_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: go test -race -cover ./...
